### ISSUE TITLE
MISSRec pretrain problem

### ISSUE THREAD

**Issue by zhanghexin0918** [gimpong/MM23-MISSRec#3]
When I execute a pre-training task for a MISSRec model, the task always terminates with an error.I've tried using two GPUs and four GPUs (4090) and the problem still appears.When using 2GPUs, it appear at 6th epoch,and 2nd epoch for 4GPUs.I don't know why the problem is occurring, so I opened an issue to get help.
Below is a detailed description of the problem：
![1710042144435](https://github.com/gimpong/MM23-MISSRec/assets/142506672/239981f8-0272-45cf-b398-a6252270bc47)
![1710042207484](https://github.com/gimpong/MM23-MISSRec/assets/142506672/36afaef3-00fa-45c4-8b38-677a2a20b880)

**Comment by gimpong** [comment]
你好！这个问题确实可能出现。这是由于MinibatchKMeans（在torchPQ中）实现了很多用cuda写的kernel函数，以加速计算，它有的时候会非法访问到torch的显存空间，这个属于底层实现的bug，可能跟硬件有关系。

一个简单粗暴的做法是，聚类不要在GPU上执行了，放到CPU上，代码改一下就好：可以在
https://github.com/gimpong/MM23-MISSRec/blob/f5563046ba249f33e1b1cfee7f9e5c4ed05f0344/cluster_utils.py#L82
把`all_tokens`移动到cpu上，同时记录移动前的device，然后在
https://github.com/gimpong/MM23-MISSRec/blob/f5563046ba249f33e1b1cfee7f9e5c4ed05f0344/cluster_utils.py#L103
插入把`cluster_idx`和`centroids`分别从cpu上移动到记录的device上。

希望对你有帮助~


#### *English Version:*
> Hello! This issue may indeed occur. It's because MinibatchKMeans (in torchPQ) has implemented many kernel functions written in CUDA to accelerate computation, and it sometimes illegally accesses torch's GPU memory space. This belongs to a bug in the underlying implementation and may be related to the hardware.
>
> A simple and crude method is to perform clustering on the CPU instead of the GPU. Just a little code modification is needed: you can move all_tokens to the CPU and record the device before the move by making changes at https://github.com/gimpong/MM23-MISSRec/blob/f5563046ba249f33e1b1cfee7f9e5c4ed05f0344/cluster_utils.py#L82, then insert at https://github.com/gimpong/MM23-MISSRec/blob/f5563046ba249f33e1b1cfee7f9e5c4ed05f0344/cluster_utils.py#L103 to move cluster_idx and centroids back to the recorded device from the CPU.
> 
> Hope this helps~

**Comment by zhanghexin0918** [comment]
From:2024年3月11日21:10:24
如果按照上述办法并没有解决问题，可以进行如下尝试：
在
https://github.com/gimpong/MM23-MISSRec/blob/70717b26ca8089ac95cb64caf7936af207cfe19d/cluster_utils.py#L82
前添加
all_tokens_device = all_tokens.device
all_tokens = all_tokens.cpu().numpy()
两行代码，并将从torchpq.clustering类中引用的MinibatchKMeans方法改为sklearn.cluster中引用MiniBatchKMeans，并按文档修改相应的调用函数名以及参数，最后将得到的cluster_idx以及centroids转为torch.tensor类型。
注：如出现数据越界问题，可将ndarray类型的cluster_idx转为np.int64后再转为torch.tensor类型。

问题出现的原因：作者使用的TorchPQ库不只包含PyTorch代码还有cuda代码，所以可能会出现与PyTorch显存管理冲突的情况，并不是代码实现上的问题。

可以参考我个人解决方式
https://github.com/zhanghexin0918/MM23-MISSRec      cluster_utils_sklearn.py

**Comment by gimpong** [comment]
Thank you for your insightful solution!

**Comment by Fanfan397** [comment]
> From:2024年3月11日21:10:24 如果按照上述办法并没有解决问题，可以进行如下尝试： 在
> 
> https://github.com/gimpong/MM23-MISSRec/blob/70717b26ca8089ac95cb64caf7936af207cfe19d/cluster_utils.py#L82
> 
> 
> 前添加
> all_tokens_device = all_tokens.device
> all_tokens = all_tokens.cpu().numpy()
> 两行代码，并将从torchpq.clustering类中引用的MinibatchKMeans方法改为sklearn.cluster中引用MiniBatchKMeans，并按文档修改相应的调用函数名以及参数，最后将得到的cluster_idx以及centroids转为torch.tensor类型。
> 注：如出现数据越界问题，可将ndarray类型的cluster_idx转为np.int64后再转为torch.tensor类型。
> 问题出现的原因：作者使用的TorchPQ库不只包含PyTorch代码还有cuda代码，所以可能会出现与PyTorch显存管理冲突的情况，并不是代码实现上的问题。
> 
> 可以参考我个人解决方式 https://github.com/zhanghexin0918/MM23-MISSRec cluster_utils_sklearn.py

你好！我根据你的地址https://github.com/zhanghexin0918/MM23-MISSRec并没有找到这个文件，我的损失训练完1轮就变成Nan了，能向您请教一下嘛

**Comment by gimpong** [comment]
@Fanfan397 您好，该issue的根源是基于的TorchPQ库包含直接使用cuda实现的kernel函数，显存管理跟pytorch的显存管理产生冲突。比如TorchPQ的cuda代码和torch申请的tensor空间有部分是重合的，产生读写冲突。

解决方案是把在GPU上聚类的操作迁移到CPU上执行，可以按照上述提示修改代码：

1. 添加两行代码；
2. 将调用torchpq.clustering的MinibatchKMeans方法，修改为调用sklearn.cluster的MiniBatchKMeans方法，注意这两个接口的入参可能需要相应修改一下；
3. 将ndarray类型的cluster_idx转为np.int64后再转为torch.tensor类型，否则会有64位（long类型）和32位（int类型）数值的隐式转换，导致索引溢出。
