### ISSUE TITLE
请教online serving的问题

### ISSUE THREAD

**Issue by FlamingJay** [gimpong/MM23-MISSRec#5]
您好，拜读了您的文章，写得非常好，有一个问题想要请教：

在线推理的时候，是类似YouTube DNN，使用faiss这类向量库，把多模态item的embeddings存在里面，然后线上计算走一遍Transformer得到 u_i么，再去向量库里面检索么？

**Comment by gimpong** [comment]
是的，这是一个双塔模型，user embedding可以离线刷好

**Comment by FlamingJay** [comment]
> 是的，这是一个双塔模型，user embedding可以离线刷好

哈？user embedding也是离线存储的？那实时的用户序列如何使用呢

**Comment by FlamingJay** [comment]
> > 是的，这是一个双塔模型，user embedding可以离线刷好
> 
> 哈？user embedding也是离线存储的？那实时的用户序列如何使用呢

如果也是离线存储的，每次请求岂不是召回结果基本都一样了

**Comment by gimpong** [comment]
是的。是否离线存储，取决于多久更新一次用户的序列历史。离线刷user embedding+缓存的使用场景是那种对实时性要求不高的；否则需要在线计算user embedding，以适应不断更新的用户行为序列。

此外，user behavior embedding一般只是单一信息源，实际应用的推荐系统还会考虑其他信息（如user profile、时间信息等），在它们之上构建一个更复杂的模型。我们的工作还没有涉及这些方面。

**Comment by FlamingJay** [comment]
> 是的。是否离线存储，取决于多久更新一次用户的序列历史。离线刷user embedding+缓存的使用场景是那种对实时性要求不高的；否则需要在线计算user embedding，以适应不断更新的用户行为序列。
> 
> 此外，user behavior embedding一般只是单一信息源，实际应用的推荐系统还会考虑其他信息（如user profile、时间信息等），在它们之上构建一个更复杂的模型。我们的工作还没有涉及这些方面。

了解。感谢回答。
