### ISSUE TITLE
损失消失问题

### ISSUE THREAD

**Issue by Fanfan397** [gimpong/MM23-MISSRec#7]
训练了一个epoch后，他出现了这样的问题：
![消失1](https://github.com/gimpong/MM23-MISSRec/assets/147038024/295c6df1-ca06-4f53-9533-d0c36bb0a682)
![消失2](https://github.com/gimpong/MM23-MISSRec/assets/147038024/64d4403d-a498-4257-b790-60d2347996dd)

**Comment by gimpong** [comment]
可以看下是不是这个问题导致的： Issue https://github.com/gimpong/MM23-MISSRec/issues/3

**Comment by Fanfan397** [comment]
> 可以看下是不是这个问题导致的： Issue #3

谢谢！确实是这个问题导致的
