### ISSUE TITLE
关于数据集图片处理的问题

### ISSUE THREAD

**Issue by MengYiia** [gimpong/MM23-MISSRec#8]
您好，看了您的工作我受益匪浅。但在自定义数据集的过程中遇到了问题，即您标注的自定义数据集说明书中没有标明图片的处理逻辑。我不太清楚视觉模态的feat3CLS该以什么顺序怎么生成，希望您能提供处理生成视觉模态.feat3CLS脚本文件，我将十分感谢。

**Comment by gimpong** [comment]
您好，图片使用huggingface提供的预训练CLIP模型处理图片的pipeline，详见[🔗](https://huggingface.co/docs/transformers/model_doc/clip)。

`.feat3CLS`是一个张量，形状为`NxD`，其中`N`是数据集item的个数，`D`是embedding的维数（比如512），如果一个item的图片是缺失的，那么对应的embedding向量置为全0。

希望能帮到您！

**Comment by MengYiia** [comment]
我明白了，十分感谢您的回复！
