### ISSUE TITLE
关于Amazon-2018-Scientific数据集统计数据问题

### ISSUE THREAD

**Issue by AlwaysFHao** [gimpong/MM23-MISSRec#9]
您好，感谢你们优秀的工作MISSRec，这篇工作给到我很大的启发，但我在对齐实验结果时出现了一些问题。我尝试直接通过Recbole框架在Amazon-Scientific数据集上运行SASRec，数据集源文件和数据处理都是遵循Recbole官方提供的内容（也进行了5-core过滤），但是各项指标都远高于你们论文中展示的SASRec的性能，甚至超过MISSRec。通过对比数据集统计信息，我发现Recbole官方的数据集统计信息与你们论文中的统计信息无法对齐，具体数据如下：#users=10716, #items=5014, #inters=74837。我也尝试自己处理Scientific数据集，通过5-core过滤后也和Recbole的信息是能对上的，但与你们论文中的数据对不上。另外我还观察到MISSRec各项实验数据貌似是与UniSRec相同的，MISSRec的源码也是继承UniSRec的项目结构去修改的。UniSRec在论文中提到其工作是遵循Recbole范式的，但现在数据集统计数据出现了偏差，我想询问一下出现这种数据集偏差问题的原因？我希望能够对齐你们的实验结果，万分感谢！

**Comment by gimpong** [comment]
为了跟UniSRec对齐，在主实验设置上，我们直接使用了UniSRec提供的交互数据。关于UniSRec的交互数据预处理细节，可以问下原作者☺️。

**Comment by AlwaysFHao** [comment]
> 为了跟UniSRec对齐，在主实验设置上，我们直接使用了UniSRec提供的交互数据。关于UniSRec的交互数据预处理细节，可以问下原作者☺️。

感谢您的迅速回复，UniSRec作者貌似在github并不活跃，因为考虑到你们还额外处理了图像模态的信息，所以我优先来询问了你们。我们暂时定位到问题差异可能是在这个过滤函数上，左边是我参照[MMSRec](https://github.com/kz-song/MMSRec)工作的处理方式修改的方法，结果是与Recbole的处理结果能对上的，右边是从你们源码中截取的过滤函数。如果可以的话，您是否可以考虑帮助我们看一下差异在哪儿呢？
![2E628B576383B1DD3B8C0749EC36645D](https://github.com/user-attachments/assets/07e46351-c1c7-4a51-9d3d-3018c303e371)

冒昧叨扰，烦请谅解！

**Comment by gimpong** [comment]
推荐领域设置调整的情况比较常见，我个人认为数据的划分和处理合理即可，具体做法可以在论文或者附录的实现细节中阐述。只要不同模型是在相同的数据集划分上训练和评估的就行了。祝好！😉

**Comment by AlwaysFHao** [comment]
> 推荐领域设置调整的情况比较常见，我个人认为数据的划分和处理合理即可，具体做法可以在论文或者附录的实现细节中阐述。只要不同模型是在相同的数据集划分上训练和评估的就行了。祝好！😉

感谢您的迅速回复以及建议，同时再次感谢你们的优秀工作！同祝好！🤗
